# render.yaml
services:
  - type: web # סוג השירות הוא Web Service (יריץ את gunicorn + Flask, והבוט ירוץ ב-thread)
    name: tradecore-vip-bot # שם השירות שלך ב-Render
    env: python # סביבת הריצה
    region: frankfurt # (אופציונלי) בחר אזור קרוב אליך, למשל פרנקפורט או אחר
    plan: free # השתמש בתוכנית החינמית (ודא שהיא זמינה לאזור ולסוג השירות)
    
    buildCommand: "pip install -r requirements.txt" # הפקודה לבניית התלויות
  startCommand:python bot_minimal.py
    # 'bot' הוא שם הקובץ bot.py (בלי הסיומת .py)
    # 'flask_app' הוא שם אובייקט ה-Flask שמוגדר ב-bot.py
    # $PORT הוא משתנה סביבה ש-Render מספק אוטומטית

    healthCheckPath: /health # נתיב לבדיקת "בריאות" בסיסית (ניצור אותו ב-Flask)

    envVars:
      - key: PYTHON_VERSION # הגדרת גרסת פייתון (מומלץ)
        value: "3.11" # התאם לגרסה שבה אתה משתמש (למשל 3.9, 3.10, 3.11)
      - key: TELEGRAM_BOT_TOKEN
        fromSecret: true # סימון שזהו ערך סודי (תצטרך להגדיר אותו בממשק של Render)
      - key: ADMIN_USER_ID
        value: "ה-ID_שלך_כאדמין" # החלף בערך האמיתי או הגדר כ-Secret
      - key: CHANNEL_ID
        value: "-100591679360" # הערך שסיפקת
      - key: GSHEET_SPREADSHEET_ID
        value: "1KABh1HP7aa2KmvnUKZDpn8USsueJ_7_wVBjrP5DyFCw" # הערך שסיפקת
      - key: GSHEET_SHEET_NAME
        value: "Sheet1" # או השם הנכון של הגיליון שלך
      - key: GSHEET_SERVICE_ACCOUNT_JSON_CONTENT # נשמור את כל תוכן ה-JSON כמשתנה סביבה
        fromSecret: true # זהו תוכן סודי וארוך
      - key: GUMROAD_PRODUCT_PERMALINK
        value: "your_gumroad_product_permalink" # החלף בערך האמיתי
      - key: PAYPAL_ME_LINK
        value: "https://www.paypal.me/ylevi376/120ILS" # הערך שסיפקת
      - key: PAYMENT_AMOUNT_ILS
        value: "120"
      # תוכל להוסיף כאן משתני סביבה נוספים מקובץ config.py לפי הצורך

    # (אופציונלי) אם אתה משתמש ב-SQLite והיית רוצה לשמור אותו באופן קבוע (כרגע אנו משתמשים ב-Google Sheets)
    # disque:
    #   name: bot-data
    #   mountPath: /var/data # הנתיב שבו יישמר הקובץ (למשל, users.db)
    #   sizeGB: 1 # גודל מינימלי (עולה כסף מעבר לתוכנית החינמית אם הדיסק לא כלול)
